In [1]:
%%sql
select * from screening_bonds_transformed sbt
order by issuer

,name,currency,issuer,isin,sector,maturity,S&P Rating,coupon,Coupon frequency,YTM (Ask),ask,Minimum size,Country of issue,Amount issued,Increment size,subordinated,EU Tax,W/Tax,Accrued days,Accrued interest
0,EGYPT 7.053% 15.01.2032,USD,Arab Republic of Egypt,XS2079842642,Sovereign,2032-01-15,B,7.05,Semi-Annual,7.158,99.375,200000,Egypt,1000000000,1000,No,Yes,No,111,2.175
1,EGYPT 7% 10.11.2028,USD,Arab Republic of Egypt,XS1504948776,Sovereign,2028-10-11,NaN,7.00,Semi-Annual,6.290,101.625,200000,Egypt,1320000000,1000,No,Yes,No,176,3.422
2,EGYPT 7.6% 01.03.2029,USD,Arab Republic of Egypt,XS1953057061,Sovereign,2029-01-03,B,7.60,Semi-Annual,6.270,103.250,200000,Egypt,1750000000,1000,No,Yes,No,65,1.372
3,EGYPT 5.8% 30.09.2027,USD,Arab Republic of Egypt,XS2391394348,Sovereign,2027-09-30,B,5.80,Semi-Annual,5.513,100.375,200000,Egypt,1125000000,1000,No,Yes,No,36,0.580
4,EGYPT 8.625% 04.02.2030,USD,Arab Republic of Egypt,XS2989586941,Sovereign,2030-04-02,B,8.63,Semi-Annual,6.521,107.000,200000,Egypt,1250000000,1000,No,Yes,No,92,2.204
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,US AMERICA 4.25% 31.01.2030,USD,United States of America,US91282CMG32,Sovereign,2030-01-31,NaN,4.25,Semi-Annual,3.959,100.777,100,USA,73885625600,100,No,Yes,No,102,1.178
1996,US AMERICA 3.625% 31.10.2030,USD,United States of America,US91282CPD73,Sovereign,2030-10-31,NaN,3.63,Semi-Annual,4.002,98.246,100,USA,74019363100,100,No,Yes,No,10,0.100
1997,US AMERICA 0% 06.08.2026,USD,United States of America,US912797RG48,Sovereign,2026-06-08,NaN,0.00,NaN,3.690,99.071,100,USA,133270264900,100,No,Yes,No,95,0.000
1998,US AMERICA 4% 15.12.2027,USD,United States of America,US91282CMB45,Sovereign,2027-12-15,NaN,4.00,Semi-Annual,3.868,100.117,100,USA,58415371000,100,No,Yes,No,148,1.617
1999,US AMERICA 1.25% 30.06.2028,USD,United States of America,US91282CCH25,Sovereign,2028-06-30,NaN,1.25,Semi-Annual,3.887,94.469,100,USA,70834102100,100,No,Yes,No,133,0.452

In [2]:
df.describe()

,coupon,YTM (Ask),ask,Minimum size,Amount issued,Increment size,Accrued days,Accrued interest
count,2000.000000,2000.000000,2000.000000,2.000000e+03,2.000000e+03,2.000000e+03,2000.000000,1920.000000
mean,3.071765,4.624286,97.347318,2.247323e+05,3.413437e+10,1.776283e+05,122.260000,0.942909
std,2.534909,11.758756,11.100350,3.872044e+06,1.386756e+11,3.873232e+06,95.830956,1.077605
min,0.000000,0.065000,3.482000,0.000000e+00,4.432300e+07,0.000000e+00,0.000000,-0.112000
25%,0.630000,2.852500,97.000000,1.000000e+02,1.250000e+09,1.000000e+02,46.000000,0.085500
50%,3.000000,3.869500,99.106500,1.000000e+03,5.000000e+09,1.000000e+03,102.000000,0.614000
75%,4.570000,4.764750,100.429500,1.000000e+05,2.895196e+10,1.000000e+03,171.000000,1.405750
max,12.400000,446.036000,127.250000,1.000000e+08,2.329542e+12,1.000000e+08,450.000000,7.705000