In [1]:
%%sql
# SELECT * FROM expected_returns_summary

,isin,ticker,name,description,region,country,trading_country,exchange,sector,industry,...,signal,weighted_agreement,composite_score,quality_tier,expected_upside_pct_zscore,filtered_upside_zscore,expected_return_prob_weighted_zscore,expected_upside_pct_pctile,filtered_upside_pctile,expected_return_prob_weighted_pctile
0,US89532M1018,TRVI,Trevi Therapeutics Inc.,Trevi Therapeutics Inc. a clinical-stage bioph...,United States and Canada,US,US,NasdaqGM,Health Care,Pharmaceuticals,...,Bullish (3/4),1.800000,47.361111,Below Avg,0.861440,1.088541,0.453066,84.482759,85.632184,85.057471
1,CNE0000016J9,600309,Wanhua Chemical Group Co. Ltd.,Wanhua Chemical Group Co. Ltd. provides polyur...,Asia / Pacific,CN,CN,SHSE,Materials,Chemicals,...,Bullish (3/4),1.446060,42.777778,Below Avg,-0.352138,-0.223046,-0.094303,34.703196,41.095890,33.333333
2,US2561631068,DOCU,DocuSign Inc.,DocuSign Inc. provides electronic signature so...,United States and Canada,US,US,NasdaqGS,Information Technology,Software,...,Bullish (3/4),1.796860,81.666667,High,0.286128,0.177260,-0.726542,71.627907,69.302326,10.697674
3,BRDESKACNOR2,DESK3,Desktop S.A.,Desktop S.A. provides fixed telephony broadban...,Latin America and Caribbean,BR,BR,BOVESPA,Communication Services,Diversified Telecommunication Services,...,Strong Bearish (0/4),0.000000,34.583333,Below Avg,-0.760624,-0.708573,-1.341131,16.455696,22.784810,10.126582
4,KYG4402L1510,1044,Hengan International Group Company Limited,Hengan International Group Company Limited an ...,Asia / Pacific,CN,HK,SEHK,Consumer Staples,Personal Care Products,...,Neutral (2/4),0.800000,61.861111,Above Avg,-1.226468,-1.247648,-0.997735,6.976744,9.302326,16.279070
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5526,BE0974259880,DIE,D'Ieteren Group SA,D'Ieteren Group SA operates as an investment c...,Europe,BE,BE,ENXTBR,Consumer Discretionary,Distributors,...,Strong Bullish (4/4),2.509890,67.048611,Above Avg,-0.609363,-0.519960,-0.333807,25.000000,33.333333,50.000000
5527,IE00BWY4ZF18,CRN,Cairn Homes plc,Cairn Homes plc operates as homebuilder in Ire...,Europe,IE,GB,LSE,Consumer Discretionary,Household Durables,...,Strong Bullish (4/4),2.886197,69.583333,Above Avg,-0.623697,-0.686970,0.339038,22.641509,19.811321,74.528302
5528,FR0000032526,GBT,Guerbet SA,Guerbet SA engages in the development and mark...,Europe,FR,FR,ENXTPA,Health Care,Health Care Equipment and Supplies,...,Bullish (3/4),1.800000,36.805556,Below Avg,-0.083692,-0.018612,-1.179450,59.836066,62.295082,9.836066
5529,CA7739151032,RGSI,Rockpoint Gas Storage Inc.,Rockpoint Gas Storage Inc. owns and operates n...,United States and Canada,CA,CA,TSX,Energy,Oil Gas and Consumable Fuels,...,Bullish (3/4),2.400000,43.229167,Below Avg,0.224001,0.242755,0.425622,74.493927,73.684211,68.421053
5530,FR0000050353,FII,Lisi S.A.,Lisi S.A. designs and produces assembly and co...,Europe,FR,FR,ENXTPA,Industrials,Aerospace and Defense,...,Strong Bullish (4/4),2.507950,68.250000,Above Avg,-0.099961,-0.139896,0.429837,55.913978,54.838710,72.043011

In [2]:
df.describe()

,reporting_interval,last_price,var_5_pct,risk_reward_ratio,expected_upside_pct,price_target_mc,prob_positive_upside,filtered_upside,kalman_estimate,expected_return_prob_weighted,...,shares_outstanding,agreement_score,weighted_agreement,composite_score,expected_upside_pct_zscore,filtered_upside_zscore,expected_return_prob_weighted_zscore,expected_upside_pct_pctile,filtered_upside_pctile,expected_return_prob_weighted_pctile
count,5531.000000,5.531000e+03,5531.000000,5531.000000,5531.000000,5.531000e+03,5531.000000,5531.000000,5.531000e+03,5531.000000,...,5.531000e+03,5531.000000,5531.000000,5531.000000,5.531000e+03,5.531000e+03,5.531000e+03,5531.000000,5531.000000,5531.000000
mean,4.950461,5.981711e+03,9.496326,3.971227,29.817500,6.943791e+03,83.516076,22.257759,6.817497e+03,8.154794,...,1.869141e+09,2.940155,1.797504,57.589258,-2.826241e-17,-2.055448e-17,-2.697776e-17,50.533357,50.533357,50.533357
std,1.523441,6.518361e+04,32.274139,20.980560,40.537331,8.011371e+04,27.371714,26.374417,7.736018e+04,10.772955,...,1.633913e+10,1.077402,0.713219,19.094731,9.947421e-01,9.947421e-01,9.947421e-01,28.870959,28.870793,28.870959
min,0.000000,3.450000e-02,-95.731522,-923.905153,-95.559316,1.006548e-01,0.000000,-28.322501,1.009076e-01,-86.003610,...,2.300090e+05,0.000000,0.000000,4.027778,-3.585899e+00,-2.783927e+00,-5.967734e+00,0.367647,0.374532,0.367647
25%,3.000000,1.400000e+01,-8.971210,0.804764,7.470292,1.819251e+01,77.283000,6.313520,1.720018e+01,4.431439,...,7.329058e+07,3.000000,1.690470,44.305556,-5.719905e-01,-5.996068e-01,-4.591436e-01,25.498134,25.498134,25.498134
50%,6.000000,4.210000e+01,5.974946,2.203161,21.893921,5.183556e+01,99.824000,17.280979,4.937621e+01,8.600008,...,2.192891e+08,3.000000,1.905430,59.819444,-1.814501e-01,-1.770961e-01,2.932568e-02,50.574713,50.574713,50.574713
75%,6.000000,1.539250e+02,22.373583,4.051807,41.509437,1.846308e+02,100.000000,31.446049,1.788339e+02,12.884093,...,8.209645e+08,4.000000,2.214527,73.333333,3.587927e-01,4.065938e-01,4.758507e-01,75.500200,75.500200,75.500200
max,6.000000,2.546000e+06,408.559703,552.342544,639.647816,3.233173e+06,100.000000,148.966064,3.066730e+06,152.431953,...,1.062010e+12,4.000000,2.886197,100.000000,9.648627e+00,6.676694e+00,1.029706e+01,100.000000,100.000000,100.000000

In [3]:
df.head(10)

,isin,ticker,name,description,region,country,trading_country,exchange,sector,industry,...,signal,weighted_agreement,composite_score,quality_tier,expected_upside_pct_zscore,filtered_upside_zscore,expected_return_prob_weighted_zscore,expected_upside_pct_pctile,filtered_upside_pctile,expected_return_prob_weighted_pctile
0,US89532M1018,TRVI,Trevi Therapeutics Inc.,Trevi Therapeutics Inc. a clinical-stage bioph...,United States and Canada,US,US,NasdaqGM,Health Care,Pharmaceuticals,...,Bullish (3/4),1.80000,47.361111,Below Avg,0.861440,1.088541,0.453066,84.482759,85.632184,85.057471
1,CNE0000016J9,600309,Wanhua Chemical Group Co. Ltd.,Wanhua Chemical Group Co. Ltd. provides polyur...,Asia / Pacific,CN,CN,SHSE,Materials,Chemicals,...,Bullish (3/4),1.44606,42.777778,Below Avg,-0.352138,-0.223046,-0.094303,34.703196,41.095890,33.333333
2,US2561631068,DOCU,DocuSign Inc.,DocuSign Inc. provides electronic signature so...,United States and Canada,US,US,NasdaqGS,Information Technology,Software,...,Bullish (3/4),1.79686,81.666667,High,0.286128,0.177260,-0.726542,71.627907,69.302326,10.697674
3,BRDESKACNOR2,DESK3,Desktop S.A.,Desktop S.A. provides fixed telephony broadban...,Latin America and Caribbean,BR,BR,BOVESPA,Communication Services,Diversified Telecommunication Services,...,Strong Bearish (0/4),0.00000,34.583333,Below Avg,-0.760624,-0.708573,-1.341131,16.455696,22.784810,10.126582
4,KYG4402L1510,1044,Hengan International Group Company Limited,Hengan International Group Company Limited an ...,Asia / Pacific,CN,HK,SEHK,Consumer Staples,Personal Care Products,...,Neutral (2/4),0.80000,61.861111,Above Avg,-1.226468,-1.247648,-0.997735,6.976744,9.302326,16.279070